apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-docker-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-docker-app
  template:
    metadata:
      labels:
        app: k8s-docker-app
    spec:
      containers:
      - name: k8s-docker-app
        image: k8s-docker-app
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10