apiVersion: v1
kind: Service
metadata:
  name: k8s-docker-app-service
spec:
  type: NodePort
  selector:
    app: k8s-docker-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30080